services:
  aws.greengrass.FleetProvisioningByClaim:
    configuration:
      awsRegion: us-west-2
      claimCertificatePath: /greengrass/v2/claim-certs/claim.pem.crt
      claimCertificatePrivateKeyPath: /greengrass/v2/claim-certs/claim.private.pem.key
      iotCredentialEndpoint: c2pkgv9n6fkyqa.credentials.iot.us-west-2.amazonaws.com
      iotDataEndpoint: a1qwhobjtvew8t-ats.iot.us-west-2.amazonaws.com
      iotRoleAlias: STR02TokenExchangeRoleAlias
      provisioningTemplate: STR02FleetProvisionTemplate
      rootCaPath: /greengrass/v2/AmazonRootCA1.pem
      rootPath: /greengrass/v2
      templateParameters:
        ThingGroupName: st_redmond_02_group
        ThingName: LAPTOP-M7NITMU2-314e5e4b09834c35999c145939942505-3c98c775-b0c9-4748-a1da-1370288b62a5
  aws.greengrass.Nucleus:
    version: 2.13.0
